<?php
namespace App\Http\Controllers;
use App\Models\DemandeAide; use App\Models\Etudiant; use App\Models\TypeAide; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
class AidesEtudiantesController extends Controller {
 public function types(Request $r){$this->admin($r);return response()->json(['success'=>true,'data'=>TypeAide::latest()->paginate($this->per($r))]);}
 public function creerType(Request $r){$this->admin($r);$d=$r->validate(['nom'=>'required|string|max:100|unique:types_aides,nom','montant_defaut'=>'nullable|numeric|min:0','periodicite'=>'required|in:mensuelle,annuelle,ponctuelle','conditions'=>'nullable|string|max:3000','actif'=>'nullable|boolean']);return response()->json(['success'=>true,'data'=>TypeAide::create($d)],201);}
 public function modifierType(Request $r,TypeAide $type){$this->admin($r);$type->update($r->validate(['nom'=>'sometimes|string|max:100|unique:types_aides,nom,'.$type->id,'montant_defaut'=>'nullable|numeric|min:0','periodicite'=>'sometimes|in:mensuelle,annuelle,ponctuelle','conditions'=>'nullable|string|max:3000','actif'=>'nullable|boolean']));return response()->json(['success'=>true,'data'=>$type->fresh()]);}
 public function index(Request $r){$q=DemandeAide::query();if(!$this->isAdmin($r))$q->where('utilisateur_id',$r->user()->id);foreach(['statut','type_aide_id']as$f)if($r->filled($f))$q->where($f,$r->input($f));if($r->filled('date_debut'))$q->whereDate('created_at','>=',$r->input('date_debut'));if($r->filled('date_fin'))$q->whereDate('created_at','<=',$r->input('date_fin'));return response()->json(['success'=>true,'data'=>$q->latest()->paginate($this->per($r))]);}
 public function store(Request $r){$d=$r->validate(['type_aide_id'=>'required|exists:types_aides,id','etudiant_id'=>'nullable|exists:etudiants,id','motif'=>'required|string|max:3000']);if(isset($d['etudiant_id']))abort_unless($this->isAdmin($r)||Etudiant::whereKey($d['etudiant_id'])->where('utilisateur_id',$r->user()->id)->exists(),403,'Étudiant non autorisé.');$demande=DemandeAide::create($d+['reference'=>'AID-'.now()->format('Ymd').'-'.strtoupper(Str::random(6)),'utilisateur_id'=>$r->user()->id]);$this->trace($demande,'creation',$r->user()->id);return response()->json(['success'=>true,'data'=>$demande],201);}
 public function soumettre(Request $r,DemandeAide $demande){$this->owner($r,$demande);abort_unless(in_array($demande->statut,['brouillon','rejetee']),422,'Demande non soumissible.');$demande->update(['statut'=>'soumise','motif_rejet'=>null]);$this->trace($demande,'soumission',$r->user()->id);return response()->json(['success'=>true,'data'=>$demande->fresh()]);}
 public function deposerPiece(Request $r,DemandeAide $demande){$this->owner($r,$demande);$d=$r->validate(['fichier'=>'required|file|mimes:pdf,jpg,jpeg,png|max:10240']);$f=$d['fichier'];$path=$f->store("aides/{$demande->id}",'local');$id=DB::table('pieces_demandes_aides')->insertGetId(['demande_aide_id'=>$demande->id,'nom_original'=>$f->getClientOriginalName(),'chemin'=>$path,'mime_type'=>$f->getMimeType(),'taille'=>$f->getSize(),'created_at'=>now(),'updated_at'=>now()]);return response()->json(['success'=>true,'data'=>DB::table('pieces_demandes_aides')->find($id)],201);}
 public function enAttente(Request $r){$this->admin($r);return response()->json(['success'=>true,'data'=>DemandeAide::whereIn('statut',['soumise','en_etude'])->latest()->paginate($this->per($r))]);}
 public function verifierPiece(Request $r,DemandeAide $demande,int $piece){$this->admin($r);$d=$r->validate(['conforme'=>'required|boolean','commentaire'=>'nullable|string|max:2000']);$p=DB::table('pieces_demandes_aides')->where('id',$piece)->where('demande_aide_id',$demande->id)->first();abort_unless($p,404);DB::table('pieces_demandes_aides')->where('id',$piece)->update($d+['verifie_par'=>$r->user()->id,'verifie_at'=>now(),'updated_at'=>now()]);$demande->update(['statut'=>'en_etude']);$this->trace($demande,'verification_piece',$r->user()->id);return response()->json(['success'=>true]);}
 public function valider(Request $r,DemandeAide $demande){$this->admin($r);abort_unless(in_array($demande->statut,['soumise','en_etude']),422,'Demande non traitable.');$pieces=DB::table('pieces_demandes_aides')->where('demande_aide_id',$demande->id);abort_unless($pieces->exists(),422,'Au moins une pièce justificative est obligatoire.');abort_if($pieces->where(fn($q)=>$q->whereNull('conforme')->orWhere('conforme',false))->exists(),422,'Toutes les pièces doivent être vérifiées conformes.');$d=$r->validate(['montant_attribue'=>'required|numeric|min:0','commentaire'=>'nullable|string|max:3000']);$demande->update(['statut'=>'validee','montant_attribue'=>$d['montant_attribue'],'commentaire_etude'=>$d['commentaire']??null,'traite_par'=>$r->user()->id,'traite_at'=>now(),'notification_at'=>now()]);$this->trace($demande,'validation',$r->user()->id);return response()->json(['success'=>true,'data'=>$demande->fresh()]);}
 public function rejeter(Request $r,DemandeAide $demande){$this->admin($r);$d=$r->validate(['motif_rejet'=>'required|string|min:3|max:3000']);$demande->update(['statut'=>'rejetee','motif_rejet'=>$d['motif_rejet'],'traite_par'=>$r->user()->id,'traite_at'=>now(),'notification_at'=>now()]);$this->trace($demande,'rejet',$r->user()->id);return response()->json(['success'=>true,'data'=>$demande->fresh()]);}
 public function show(Request $r,DemandeAide $demande){$this->access($r,$demande);$d=$demande->toArray();$d['pieces']=DB::table('pieces_demandes_aides')->where('demande_aide_id',$demande->id)->get();$d['historique']=DB::table('historiques_aides')->where('demande_aide_id',$demande->id)->latest()->get();return response()->json(['success'=>true,'data'=>$d]);}
 private function trace(DemandeAide $d,string $a,int $u):void{DB::table('historiques_aides')->insert(['demande_aide_id'=>$d->id,'action'=>$a,'details'=>json_encode($d->fresh()->toArray()),'utilisateur_id'=>$u,'created_at'=>now(),'updated_at'=>now()]);}
 private function isAdmin(Request $r):bool{return strtolower((string)$r->user()->loadMissing('role')->role?->libelle)==='administrateur';}private function admin(Request $r):void{abort_unless($this->isAdmin($r),403,'Réservé aux administrateurs.');}private function owner(Request $r,DemandeAide $d):void{abort_unless($d->utilisateur_id===$r->user()->id,403,'Accès non autorisé.');}private function access(Request $r,DemandeAide $d):void{abort_unless($this->isAdmin($r)||$d->utilisateur_id===$r->user()->id,403,'Accès non autorisé.');}private function per(Request $r):int{return min(max($r->integer('per_page',15),1),100);}
}
