<?php
namespace App\Http\Controllers;
use App\Models\AttributionBourse; use App\Models\Etudiant; use App\Models\TypeBourse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class BoursesController extends Controller {
 public function types(Request $r){$this->admin($r);return response()->json(['success'=>true,'data'=>TypeBourse::latest()->paginate($this->per($r))]);}
 public function creerType(Request $r){$this->admin($r);$d=$r->validate(['nom'=>'required|string|max:100|unique:types_bourses,nom','montant_mensuel'=>'required|numeric|min:0','duree_mois'=>'required|integer|min:1|max:60','conditions'=>'nullable|string|max:3000','actif'=>'nullable|boolean']);return response()->json(['success'=>true,'data'=>TypeBourse::create($d)],201);}
 public function modifierType(Request $r,TypeBourse $type){$this->admin($r);$type->update($r->validate(['nom'=>'sometimes|string|max:100|unique:types_bourses,nom,'.$type->id,'montant_mensuel'=>'sometimes|numeric|min:0','duree_mois'=>'sometimes|integer|min:1|max:60','conditions'=>'nullable|string|max:3000','actif'=>'nullable|boolean']));return response()->json(['success'=>true,'data'=>$type->fresh()]);}
 public function etudiants(Request $r){$this->admin($r);$q=Etudiant::query();foreach(['filiere','niveau'] as $f)if($r->filled($f))$q->where($f,$r->input($f));return response()->json(['success'=>true,'data'=>$q->latest()->paginate($this->per($r))]);}
 public function creerEtudiant(Request $r){$this->admin($r);$d=$r->validate(['matricule'=>'required|string|max:100|unique:etudiants,matricule','nom'=>'required|string|max:100','prenom'=>'required|string|max:100','filiere'=>'required|string|max:100','niveau'=>'required|string|max:100','utilisateur_id'=>'nullable|exists:utilisateurs,id']);return response()->json(['success'=>true,'data'=>Etudiant::create($d)],201);}
 public function modifierEtudiant(Request $r,Etudiant $etudiant){$this->admin($r);$etudiant->update($r->validate(['matricule'=>'sometimes|string|max:100|unique:etudiants,matricule,'.$etudiant->id,'nom'=>'sometimes|string|max:100','prenom'=>'sometimes|string|max:100','filiere'=>'sometimes|string|max:100','niveau'=>'sometimes|string|max:100','utilisateur_id'=>'nullable|exists:utilisateurs,id']));return response()->json(['success'=>true,'data'=>$etudiant->fresh()]);}
 public function attribuer(Request $r){$this->admin($r);$d=$r->validate(['etudiant_id'=>'required|exists:etudiants,id','type_bourse_id'=>'required|exists:types_bourses,id','date_debut'=>'required|date','date_fin'=>'nullable|date|after_or_equal:date_debut','montant_mensuel'=>'nullable|numeric|min:0','commentaire'=>'nullable|string|max:3000']);$type=TypeBourse::findOrFail($d['type_bourse_id']);$fin=$d['date_fin']??now()->parse($d['date_debut'])->addMonths($type->duree_mois)->subDay()->toDateString();$a=AttributionBourse::create($d+['date_fin'=>$fin,'montant_mensuel'=>$d['montant_mensuel']??$type->montant_mensuel,'attribue_par'=>$r->user()->id]);$this->tracer($a,'attribution',$r->user()->id);return response()->json(['success'=>true,'data'=>$a],201);}
 public function attributions(Request $r){$this->admin($r);$q=AttributionBourse::query();foreach(['etudiant_id','type_bourse_id','statut']as$f)if($r->filled($f))$q->where($f,$r->input($f));return response()->json(['success'=>true,'data'=>$q->latest()->paginate($this->per($r))]);}
 public function beneficiaires(Request $r){$this->admin($r);$q=AttributionBourse::query()->join('etudiants','etudiants.id','=','attributions_bourses.etudiant_id')->join('types_bourses','types_bourses.id','=','attributions_bourses.type_bourse_id')->select('attributions_bourses.*','etudiants.nom','etudiants.prenom','etudiants.filiere','etudiants.niveau','types_bourses.nom as type_bourse');foreach(['filiere','niveau']as$f)if($r->filled($f))$q->where('etudiants.'.$f,$r->input($f));if($r->filled('type_bourse_id'))$q->where('attributions_bourses.type_bourse_id',$r->input('type_bourse_id'));return response()->json(['success'=>true,'data'=>$q->paginate($this->per($r))]);}
 public function echeances(Request $r){$this->admin($r);$jours=min(max($r->integer('jours',30),1),365);return response()->json(['success'=>true,'data'=>AttributionBourse::where('statut','active')->whereBetween('date_fin',[today(),today()->addDays($jours)])->orderBy('date_fin')->paginate($this->per($r))]);}
 public function renouveler(Request $r,AttributionBourse $attribution){$this->admin($r);abort_unless($attribution->statut==='active',422,'Bourse non renouvelable.');$d=$r->validate(['date_fin'=>'nullable|date','commentaire'=>'nullable|string|max:3000']);if(isset($d['date_fin']))abort_unless(now()->parse($d['date_fin'])->gt($attribution->date_fin),422,'La nouvelle date de fin doit être postérieure à la date de fin actuelle.');$type=TypeBourse::findOrFail($attribution->type_bourse_id);$attribution->update(['date_fin'=>$d['date_fin']??$attribution->date_fin->copy()->addMonths($type->duree_mois)->toDateString(),'commentaire'=>$d['commentaire']??$attribution->commentaire]);$this->tracer($attribution,'renouvellement',$r->user()->id);return response()->json(['success'=>true,'data'=>$attribution->fresh()]);}
 public function historique(Request $r,Etudiant $etudiant){$this->admin($r);$q=DB::table('historiques_bourses')->where('etudiant_id',$etudiant->id);if($r->filled('date_debut'))$q->whereDate('created_at','>=',$r->input('date_debut'));if($r->filled('date_fin'))$q->whereDate('created_at','<=',$r->input('date_fin'));return response()->json(['success'=>true,'data'=>$q->latest()->paginate($this->per($r))]);}
 private function tracer(AttributionBourse $a,string $action,int $u):void{DB::table('historiques_bourses')->insert(['etudiant_id'=>$a->etudiant_id,'attribution_bourse_id'=>$a->id,'action'=>$action,'details'=>json_encode($a->fresh()->toArray()),'utilisateur_id'=>$u,'created_at'=>now(),'updated_at'=>now()]);}
 private function admin(Request $r):void{abort_unless(strtolower((string)$r->user()->loadMissing('role')->role?->libelle)==='administrateur',403,'Réservé aux administrateurs.');}private function per(Request $r):int{return min(max($r->integer('per_page',15),1),100);}
}
